spring:
  application:
    name: api-gateway

server:
  port: 11101

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11001/eureka/

zuul:
  host:
    max-total-connections: 2000
    max-per-route-connections: 1000
  routes:
    eureka-client:
      path: /client/**
      sensitiveHeaders:
        strip-prefix: true
        service-id: eureka-client